name: Security Scan — Insecure Web App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  pages: write
  id-token: write

jobs:
  security-scan:
    uses: ananthu3212/shift-left-security-thesis/.github/workflows/security-scan-reusable.yml@main
    with:
      docker-image-name: insecure-web
      semgrep-config: p/python
      enable-flask-rules: true
      enable-dast: true
      app-start-command: 'FLASK_APP=app/app.py flask run --host=0.0.0.0 --port=5000'
      app-port: '5000'
      trivy-severity: HIGH,CRITICAL
      fail-on-findings: false
    secrets: inherit